### ISSUE TITLE
Love the Weapon, but does not seem to work on tablets.

### ISSUE THREAD

**Issue by InnovationAgainstDarkness** [XanTheDragon/FastCastAPIDocs#2]
I have tested the weapon on a laptop and it works great, but it does not seem to function on tablets.

I have tested on an I-Pad Mini and an Amazon Fire Tablet. Weapon does not work on either.

**Comment by EtiTheSpirit** [comment]
Are you talking about the free model weapon I give? It's designed for usage on a computer. I rely on users to be able to understand the requirements for UserInputService so that they may implement mobile support to their guns themselves.

**Comment by EtiTheSpirit** [comment]
I'm going to assume that the response I gave was the problem you were having and close this issue for now.
