### ISSUE TITLE
Bullets going through ground

### ISSUE THREAD

**Issue by farr-c** [XanTheDragon/FastCastAPIDocs#4]
Even with piercing off, there is a rare chance that the bullets will go through the ground. I've only noticed it with ground and never with walls, the more gravity and less speed, the more likely this is to occur. 

The raycast seems to not detect the hit despite the ray visibly connecting with it, so it might be roblox sided.

https://gyazo.com/a03431d337f185aa2b790a4fb9f15a00

**Comment by EtiTheSpirit** [comment]
Just so you know, I'm still looking into this. I really don't know why it's happening.

**Comment by EtiTheSpirit** [comment]
A really late reply (my mistake) but this has been resolved as of version 10.0.0. Thank you for your patience.
