### ISSUE TITLE
rayHitEvent for distanceTravelled > distance missing segmentVelocity

### ISSUE THREAD

**Issue by DoidoYo** [XanTheDragon/FastCastAPIDocs#6]
Currently you have 
```
if distanceTravelled > distance then
	connection:Disconnect()
	rayHitEvent:Fire(nil, lastPoint, nil, nil, segmentVelocity, cosmeticBulletObject)
end
```

it is missing the `segmentVelocity` (added on the latest version)

`rayHitEvent:Fire(nil, lastPoint, nil, nil, segmentVelocity, cosmeticBulletObject)` should fix it

love the lib!

**Comment by EtiTheSpirit** [comment]
I'm late on this, but it was patched (See [this post on the DevForums](https://devforum.roblox.com/t/making-a-combat-game-with-ranged-weapons-fastcast-may-be-the-module-for-you/133474/290?u=etithespirit)). Thanks for the report.
